# Generated by Django 5.0.3 on 2024-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(through='watchlist.WatchList', to='movies.movie'),
        ),
    ]
