# Generated by Django 5.0.3 on 2024-03-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
    ]
