services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./recommendation:/src/recommendation
      - ./envs:/src/envs
      - ./manage.py:/src/manage.py
      - ./pyproject.toml:/src/pyproject.toml
      - ./poetry.lock:/src/poetry.lock
      - .:/src:z
    env_file: ./envs/.postgres
    depends_on:
      - db
    command: /start

  db:
    image: postgres:14
    env_file: ./envs/.postgres
    ports:
      - "5432:5432"
